[package]
name = "serde_rlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.133", features = ['derive'] }
paste = "1.0"
serde_bytes = "0.11"
byteorder = "1.4.3"
